Repository book-worm-2010/book-worm-fe, pull requests merged in 2021-04, with the labels that each got.

#16 Ch/feature/setup components
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/BookContainer/BookContainer.js
  src/BookContainer/_BookContainer.scss
  src/Card/Card.js
  src/Card/_Card.scss
  src/Home/Home.js
  src/Home/_Home.scss
  src/NewBookForm/NewBookForm.js
  src/NewBookForm/NewBookForm.scss
  src/_App.scss
  src/index.js
  src/index.scss
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: MVP, Student, enhancement

#17 Feature/student interface architecture
  book-worm-fe/.gitignore
  book-worm-fe/README.md
  book-worm-fe/package-lock.json
  book-worm-fe/package.json
  book-worm-fe/public/favicon.ico
  book-worm-fe/public/index.html
  book-worm-fe/public/logo192.png
  book-worm-fe/public/logo512.png
  book-worm-fe/public/manifest.json
  book-worm-fe/public/robots.txt
  book-worm-fe/src/App.css
  book-worm-fe/src/App.js
  book-worm-fe/src/App.test.js
  book-worm-fe/src/index.css
  book-worm-fe/src/index.js
  book-worm-fe/src/logo.svg
  book-worm-fe/src/reportWebVitals.js
  book-worm-fe/src/setupTests.js
  src/BookDetails/BookDetails.js
  src/BookDetails/_BookDetails.scss
  src/Card/Card.js
  src/FinishBookForm/FinishBookForm.js
  src/FinishBookForm/_FinishBookForm.scss
  src/NewBookForm/_NewBookForm.scss
  src/NewBookMarkForm/NewBookMarkForm.js
  src/NewBookMarkForm/_NewBookMarkForm.scss
Labels: Front End, MVP, Student

#18 Ch/feature/set colors
  public/assets/BookWorm.svg
  public/assets/rainbow.svg
  src/index.scss
  src/style/_extends.scss
  src/style/_reset.scss
  src/style/_variables.scss
Labels: Front End, MVP, Student, enhancement

#19 kd/feature/post book
  src/apiCalls.js
Labels: api calls, temporary solution

#22 Feature/implement rainbow path
  package-lock.json
  package.json
  src/App/_App.scss
  src/BookContainer/BookContainer.js
  src/BookContainer/_BookContainer.scss
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/CurrentBookRainbow/CurrentBookRainbow.scss
  src/Home/Home.js
  src/Home/_Home.scss
  src/assets/BookWormWaves.svg
  src/assets/openbook.png
  src/assets/openbook.svg
  src/assets/storytelling.svg
  src/assets/topsoil.svg
  src/assets/worm.png
  src/index.scss
Labels: Front End, MVP, Student, enhancement, temporary solution

#23 Feature/header
  src/App/App.js
  src/Card/Card.js
  src/Card/_Card.scss
  src/Header/Header.js
  src/Header/_Header.scss
  src/Home/Home.js
  src/NewBookForm/NewBookForm.js
  src/NewBookForm/_NewBookForm.scss
  src/apiCalls.js
  src/assets/apple.svg
  src/assets/star.svg
  src/index.scss
Labels: Front End, MVP, Student, api calls, documentation, enhancement

#25 Feature/current book connections
  package-lock.json
  package.json
  src/App/App.js
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/Home/Home.js
  src/apiCalls.js
Labels: Front End, Student, api calls, enhancement

#29 Feature/header search style
  src/Card/_Card.scss
  src/Header/Header.js
  src/Header/_Header.scss
  src/Home/_Home.scss
  src/NewBookForm/NewBookForm.js
  src/NewBookForm/_NewBookForm.scss
  src/assets/exit.png
  src/assets/home.svg
  src/assets/mountain.svg
  src/assets/sandcastle.svg
  src/style/_variables.scss
Labels: Front End, Student, enhancement

#28 Feature/oauth
  package-lock.json
  package.json
  src/App/App.js
  src/Header/Header.js
  src/Home/_Home.scss
  src/Login/Login.js
  src/Login/Login.scss
  src/Logout/Logout.js
  src/assets/loginDisplay.svg
  src/index.scss
  src/utils/refreshToken.js
Labels: Front End, MVP, Student, enhancement

#30 Feature/bookmark style
  package-lock.json
  src/App/App.js
  src/App/_App.scss
  src/BookDetails/BookDetails.js
  src/BookDetails/_BookDetails.scss
  src/Card/_Card.scss
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/FinishBookForm/FinishBookForm.js
  src/FinishBookForm/_FinishBookForm.scss
  src/Header/Header.js
  src/Header/_Header.scss
  src/Home/Home.js
  src/NewBookForm/NewBookForm.js
  src/NewBookMarkForm/NewBookMarkForm.js
  src/NewBookMarkForm/_NewBookMarkForm.scss
  src/StarRating/StarRating.js
  src/StarRating/StarRating.scss
  src/index.scss
  src/style/_variables.scss
Labels: Front End, MVP, Student, enhancement

#31 Feature/style animations
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App/App.js
  src/Card/_Card.scss
  src/Celebration/Celebration.js
  src/Celebration/Celebration.scss
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/CurrentBookRainbow/CurrentBookRainbow.scss
  src/FinishBookForm/FinishBookForm.js
  src/Header/Header.js
  src/Header/_Header.scss
  src/Home/Home.js
  src/Login/Login.js
  src/Login/Login.scss
  src/Logout/Logout.js
  src/Logout/Logout.scss
  src/NewBookForm/NewBookForm.js
  src/NewBookForm/_NewBookForm.scss
  src/assets/confetti.svg
  src/assets/donut.svg
  src/assets/flower.svg
  src/assets/plainApple.svg
  src/assets/redBalloon.svg
  src/assets/sushi.svg
  src/assets/yellowBalloon.svg
  src/index.scss
Labels: Front End, MVP, Student, enhancement, extension

#32 Feature/home route
  src/App/App.js
  src/BookDetails/BookDetails.js
  src/Header/Header.js
  src/Home/Home.js
  src/Login/Login.js
  src/Logout/Logout.js
Labels: Front End

#35 Feature/refactor accessibility animations
  public/manifest.json
  src/App/App.js
  src/BookDetails/BookDetails.js
  src/Celebration/Celebration.js
  src/Celebration/Celebration.scss
  src/CurrentBookRainbow/CurrentBookRainbow.scss
  src/FinishBookForm/FinishBookForm.js
  src/Header/_Header.scss
  src/Home/Home.js
  src/Home/_Home.scss
  src/Login/Login.js
  src/Login/Login.scss
  src/Logout/Logout.js
  src/NewBookForm/NewBookForm.js
Labels: Front End, MVP, Student, enhancement

#38 Feature/error handling
  package-lock.json
  package.json
  public/index.html
  src/BookDetails/BookDetails.js
  src/BookDetails/_BookDetails.scss
  src/Card/Card.js
  src/Card/_Card.scss
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/FinishBookForm/_FinishBookForm.scss
  src/Header/Header.js
  src/Header/_Header.scss
  src/Home/Home.js
  src/Login/Login.js
  src/Logout/Logout.js
  src/Logout/Logout.scss
  src/NewBookForm/NewBookForm.js
  src/NewBookForm/_NewBookForm.scss
  src/NewBookMarkForm/NewBookMarkForm.js
  src/NewBookMarkForm/_NewBookMarkForm.scss
  src/assets/bookmark.jpg
  src/assets/exit.png
  src/assets/openBookBackground.png
  src/style/_variables.scss
Labels: Front End, Student, enhancement

#42 Feature/testing
  cypress.json
  cypress/integration/Home_spec.js
  cypress/integration/login_spec.js
  package-lock.json
  package.json
  src/FinishBookForm/FinishBookForm.js
Labels: testing

#47 Add readme
  README.md
Labels: Front End, chore

#49 Feature/refactor finish book form
  src/BookDetails/BookDetails.js
  src/BookDetails/_BookDetails.scss
  src/Card/_Card.scss
  src/Celebration/Celebration.js
  src/Celebration/Celebration.scss
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/FinishBookForm/FinishBookForm.js
  src/FinishBookForm/_FinishBookForm.scss
  src/FinishedBookCard/FinishedBookCard.js
  src/FinishedBookCard/_FinishedBookCard.scss
  src/FinishedBooks/FinishedBooks.js
  src/FinishedBooks/_FinishedBooks.scss
  src/Header/Header.js
  src/Header/_Header.scss
  src/Home/Home.js
  src/Home/_Home.scss
  src/Login/Login.js
  src/Login/Login.scss
  src/Logout/Logout.js
  src/Logout/Logout.scss
  src/NewBookForm/NewBookForm.js
  src/NewBookForm/_NewBookForm.scss
  src/NewBookMarkForm/NewBookMarkForm.js
  src/NewBookMarkForm/_NewBookMarkForm.scss
  src/apiCalls.js
  src/index.scss
  src/style/_extends.scss
  src/style/_variables.scss
  src/utils/refreshToken.js
Labels: Front End, Student

#50 Fix/error handling for book search
  src/FinishBookForm/FinishBookForm.js
  src/NewBookForm/NewBookForm.js
Labels: Front End, bug
