Repository book-worm-2010/book-worm-fe, pull requests merged in 2021-05, with the labels that each got.

#51 Refactor styling
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/CurrentBookRainbow/CurrentBookRainbow.scss
  src/FinishedBookCard/_FinishedBookCard.scss
  src/FinishedBooks/_FinishedBooks.scss
  src/Header/_Header.scss
  src/Home/Home.js
  src/Home/_Home.scss
  src/Login/Login.scss
  src/Logout/Logout.scss
  src/NewBookForm/_NewBookForm.scss
  src/assets/mountain2.svg
  src/assets/sandcastle2.svg
  src/assets/sandhill2.svg
  src/assets/topsoil.svg
  src/assets/trees2.svg
Labels: Student, enhancement

#52 Feature/friends
  src/App/App.js
  src/FriendList/FriendList.js
  src/FriendList/FriendList.scss
  src/assets/BookWormBeanie.svg
  src/assets/BookWormHat.svg
  src/assets/BookWormShoes.svg
  src/assets/BookWormStache.svg
  src/index.scss
Labels: Front End, enhancement

#53 Feature/finished book reviews
  src/CurrentBookRainbow/CurrentBookRainbow.js
  src/FinishedBookCard/FinishedBookCard.js
  src/FinishedBookCard/_FinishedBookCard.scss
  src/FinishedBooks/FinishedBooks.js
  src/Home/Home.js
Labels: enhancement
